#!/bin/bash

echo " * Installing dependencies..."

sudo aptitude install \
build-essential \
libsdl1.2-dev \
libsdl1.2debian \
libsdl-gfx1.2-4 \
libsdl-gfx1.2-dev \
libsdl-image1.2 \
libsdl-image1.2-dev \
libsdl-mixer1.2 \
libsdl-mixer1.2-dev \
libsdl-net1.2 \
libsdl-net1.2-dev \
libsdl-ttf2.0-0 \
libsdl-ttf2.0-dev
